# Generated by Django 4.2.8 on 2023-12-11 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
